service:
  name: samples-hello-serverless

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  greetings:
    handler: src/handler/greetings.hello
    events:
      - http:
          method: get
          path: hello
  systems:
    handler: src/handler/systems.handle
    events:
      - http:
          method: get
          path: version
